/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author user
 */
public class MenuBangun2d extends javax.swing.JFrame {

    /**
     * Creates new form MenuBangun2d
     */
    public MenuBangun2d() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNPP = new javax.swing.JToggleButton();
        BTNS = new javax.swing.JToggleButton();
        BTNL = new javax.swing.JToggleButton();
        BTNB = new javax.swing.JToggleButton();
        BTNK = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Menu Bangun 2D");

        BTNPP.setBackground(new java.awt.Color(102, 255, 102));
        BTNPP.setText("LUAS PERSEGI PANJANG");
        BTNPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPPActionPerformed(evt);
            }
        });

        BTNS.setBackground(new java.awt.Color(102, 255, 102));
        BTNS.setText("LUAS SEGITIGA");
        BTNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSActionPerformed(evt);
            }
        });

        BTNL.setBackground(new java.awt.Color(102, 255, 102));
        BTNL.setText("LUAS LINGKARAN");
        BTNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLActionPerformed(evt);
            }
        });

        BTNB.setBackground(new java.awt.Color(102, 255, 102));
        BTNB.setText("VOLUME BALOK");
        BTNB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBActionPerformed(evt);
            }
        });

        BTNK.setBackground(new java.awt.Color(255, 51, 51));
        BTNK.setText("KELUAR");
        BTNK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNPP, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNS, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNL, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNK, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(BTNPP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNK)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPPActionPerformed
        // TODO add your handling code here:
        
        LUASPERSEGIPANJANG A = new LUASPERSEGIPANJANG();
        this.dispose();
        A.show();
       
    }//GEN-LAST:event_BTNPPActionPerformed

    private void BTNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSActionPerformed
        // TODO add your handling code here:
        LuasSegitiga L = new LuasSegitiga();
        this.dispose();
        L.show();
    }//GEN-LAST:event_BTNSActionPerformed

    private void BTNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLActionPerformed
        // TODO add your handling code here:
        LuasLingkaran Ls = new LuasLingkaran();
        this.dispose();
        Ls.show();
        
    }//GEN-LAST:event_BTNLActionPerformed

    private void BTNBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBActionPerformed
        // TODO add your handling code here:LuasLingkaran Ls = new LuasLingkaran();
        VolumeBalok VB = new VolumeBalok();
        this.dispose();
        VB.show();
    }//GEN-LAST:event_BTNBActionPerformed

    private void BTNKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BTNKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBangun2d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBangun2d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBangun2d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBangun2d.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuBangun2d().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTNB;
    private javax.swing.JToggleButton BTNK;
    private javax.swing.JToggleButton BTNL;
    private javax.swing.JToggleButton BTNPP;
    private javax.swing.JToggleButton BTNS;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
