/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author user
 */
public class PEGAWAI extends javax.swing.JFrame {
int gp = 0;
        int tj = 0;
    /**
     * Creates new form PEGAWAI
     */
    public PEGAWAI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BTNPROSES = new javax.swing.JToggleButton();
        BTNKELUAR = new javax.swing.JToggleButton();
        BTNBERSIH = new javax.swing.JToggleButton();
        NIP = new javax.swing.JTextField();
        NAMA = new javax.swing.JTextField();
        JABATAN = new javax.swing.JTextField();
        GAJIPEGAWAI = new javax.swing.JTextField();
        TUNJANGANJABATAN = new javax.swing.JTextField();
        GAJIPEGAWAI2 = new javax.swing.JTextField();
        POTONGANBPJS = new javax.swing.JTextField();
        GAJIBERSIH = new javax.swing.JTextField();
        KODEJABATAN = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Input Data Gaji Pegawai");

        jLabel2.setText("NIP");

        jLabel3.setText("Kode Jabatan");

        jLabel4.setText("NAMA");

        jLabel5.setText("JABATAN");

        jLabel6.setText("GAJI POKOK PEGAWAI");

        jLabel7.setText("Gaji Pegawai");

        jLabel8.setText("Tunjangan Jabatan");

        jLabel9.setText("Potongan BPJS");

        jLabel10.setText("Gaji Bersih");

        BTNPROSES.setBackground(new java.awt.Color(51, 255, 102));
        BTNPROSES.setText("PROSES");
        BTNPROSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPROSESActionPerformed(evt);
            }
        });

        BTNKELUAR.setBackground(new java.awt.Color(255, 102, 102));
        BTNKELUAR.setText("KELUAR");
        BTNKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKELUARActionPerformed(evt);
            }
        });

        BTNBERSIH.setBackground(new java.awt.Color(255, 255, 255));
        BTNBERSIH.setText("BERSIH");
        BTNBERSIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBERSIHActionPerformed(evt);
            }
        });

        NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMAActionPerformed(evt);
            }
        });

        JABATAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JABATANActionPerformed(evt);
            }
        });

        GAJIPEGAWAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAJIPEGAWAIActionPerformed(evt);
            }
        });

        GAJIPEGAWAI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAJIPEGAWAI2ActionPerformed(evt);
            }
        });

        POTONGANBPJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POTONGANBPJSActionPerformed(evt);
            }
        });

        GAJIBERSIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GAJIBERSIHActionPerformed(evt);
            }
        });

        KODEJABATAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KODE JABATAN ANDA:", "MGR", "HRD", "SKR", "STF", "SEC" }));
        KODEJABATAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KODEJABATANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNPROSES, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(BTNKELUAR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(BTNBERSIH, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GAJIBERSIH)
                                            .addComponent(GAJIPEGAWAI2)
                                            .addComponent(TUNJANGANJABATAN)
                                            .addComponent(POTONGANBPJS))
                                        .addGap(35, 35, 35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(KODEJABATAN, 0, 173, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GAJIPEGAWAI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JABATAN, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NIP, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)))
                        .addGap(107, 107, 107))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(NIP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(KODEJABATAN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JABATAN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GAJIPEGAWAI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TUNJANGANJABATAN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GAJIPEGAWAI2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(POTONGANBPJS, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GAJIBERSIH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNPROSES)
                            .addComponent(BTNKELUAR)
                            .addComponent(BTNBERSIH)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNPROSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPROSESActionPerformed
            // TODO add your handling code here:private void BTNPROSESActionPerformed(java.awt.event.ActionEvent evt) {                                          
    
    if (KODEJABATAN.getSelectedItem()=="MGR"){
        GAJIPEGAWAI2.setText("Rp. 8.450.000");
        POTONGANBPJS.setText("Rp. 130.000");
        GAJIBERSIH.setText("Rp. 8.320.000 ");
        
      
    } else if (KODEJABATAN.getSelectedItem()=="HRD"){
        GAJIPEGAWAI2.setText("Rp. 6.250.000");
        POTONGANBPJS.setText("Rp. 100.000");
        GAJIBERSIH.setText("Rp. 6.275.000 ");
    } 
    else if (KODEJABATAN.getSelectedItem()=="SKR"){
        GAJIPEGAWAI2.setText("Rp. 4.600.000");
        POTONGANBPJS.setText("Rp 80.000");
        GAJIBERSIH.setText("Rp. 4.520.000 ");
    }  else if (KODEJABATAN.getSelectedItem()=="STF"){
        GAJIPEGAWAI2.setText("Rp. 3.300.000");
        POTONGANBPJS.setText("Rp. 60.000");
        GAJIBERSIH.setText("Rp. 3.240.000 ");
}  else if (KODEJABATAN.getSelectedItem()=="SEC"){
        GAJIPEGAWAI2.setText("Rp. 1.575.000");
        POTONGANBPJS.setText("Rp. 30.000");
        GAJIBERSIH.setText("Rp. 1.545.000 ");
}
  


    }//GEN-LAST:event_BTNPROSESActionPerformed

    private void BTNKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKELUARActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_BTNKELUARActionPerformed

    private void BTNBERSIHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBERSIHActionPerformed
        // TODO add your handling code here:
        NIP.setText("");
         NAMA.setText("");
          JABATAN.setText(""); 
           GAJIPEGAWAI.setText("");
            TUNJANGANJABATAN.setText("");
             GAJIPEGAWAI2.setText("");
              POTONGANBPJS.setText("");
               GAJIBERSIH.setText("");
          
    }//GEN-LAST:event_BTNBERSIHActionPerformed

    private void NAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMAActionPerformed

    private void GAJIPEGAWAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAJIPEGAWAIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GAJIPEGAWAIActionPerformed

    private void JABATANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JABATANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JABATANActionPerformed

    private void KODEJABATANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KODEJABATANActionPerformed
        // TODO add your handling code here:
        
        String kode = (String) KODEJABATAN.getSelectedItem();

    if (kode.equals("KODE JABATAN ANDA:")) {
        JABATAN.setText("");
        GAJIPEGAWAI.setText("");
        TUNJANGANJABATAN.setText("");
    } else if (kode.equals("MGR")) {
        JABATAN.setText("Manager");
        GAJIPEGAWAI.setText("6500000");
        TUNJANGANJABATAN.setText("1950000");
    } else if (kode.equals("HRD")) {
        JABATAN.setText("Personalia");
        GAJIPEGAWAI.setText("5000000");
        TUNJANGANJABATAN.setText("1250000");
    } else if (kode.equals("SKR")) {
        JABATAN.setText("Sekretaris");
        GAJIPEGAWAI.setText("4000000");
        TUNJANGANJABATAN.setText("600000");
    } else if (kode.equals("STF")) {
        JABATAN.setText("Staff");
        GAJIPEGAWAI.setText("3000000");
        TUNJANGANJABATAN.setText("300000");
    } else if (kode.equals("SEC")) {
        JABATAN.setText("Security");
        GAJIPEGAWAI.setText("1500000");
        TUNJANGANJABATAN.setText("75000");
    }

 
    }//GEN-LAST:event_KODEJABATANActionPerformed

    private void GAJIPEGAWAI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAJIPEGAWAI2ActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_GAJIPEGAWAI2ActionPerformed

    private void POTONGANBPJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POTONGANBPJSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POTONGANBPJSActionPerformed

    private void GAJIBERSIHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GAJIBERSIHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GAJIBERSIHActionPerformed
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PEGAWAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PEGAWAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PEGAWAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PEGAWAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PEGAWAI().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTNBERSIH;
    private javax.swing.JToggleButton BTNKELUAR;
    private javax.swing.JToggleButton BTNPROSES;
    private javax.swing.JTextField GAJIBERSIH;
    private javax.swing.JTextField GAJIPEGAWAI;
    private javax.swing.JTextField GAJIPEGAWAI2;
    private javax.swing.JTextField JABATAN;
    private javax.swing.JComboBox<String> KODEJABATAN;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NIP;
    private javax.swing.JTextField POTONGANBPJS;
    private javax.swing.JTextField TUNJANGANJABATAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
