/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author user
 */
public class Perjalanan extends javax.swing.JFrame {

     double RealHarga ;
    double RealHargaaa = 0;
        double discount = 0;
        double HargaPembayaran = 0;



    /**
     * Creates new form Perjalanan
     */
    public Perjalanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtfield1 = new javax.swing.JTextField();
        txtfield2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtfield3 = new javax.swing.JTextField();
        txtfield4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PulangPergi = new javax.swing.JRadioButton();
        Sejalan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtfield5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfield6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Cash = new javax.swing.JRadioButton();
        Kredit = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        txtfield7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtfield8 = new javax.swing.JTextField();
        btnjumlahharga = new javax.swing.JToggleButton();
        btnHargaBayar = new javax.swing.JToggleButton();
        btnhapus = new javax.swing.JToggleButton();
        btnkeluar = new javax.swing.JToggleButton();
        Kembalibtn = new javax.swing.JToggleButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("JADWAL PENERBANGAN PESAWAT");

        jLabel2.setText("BANDARA INTERNASIONAL SOEKARNO");

        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Dipilih", "GARUDA", "MERPATI", "MANDALA", "LION AIR", "SEMPATI" }));
        Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Pesawat");

        jLabel4.setText("Route");

        txtfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Tiket");

        jLabel6.setText("Jumlah Dibeli");

        jLabel7.setText("Jumlah Harga");

        txtfield3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield3ActionPerformed(evt);
            }
        });

        txtfield4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Jenis Perjalanan");

        buttonGroup1.add(PulangPergi);
        PulangPergi.setText("Pulang Pergi");
        PulangPergi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulangPergiActionPerformed(evt);
            }
        });

        buttonGroup1.add(Sejalan);
        Sejalan.setText("Sejalan");
        Sejalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SejalanActionPerformed(evt);
            }
        });

        jLabel9.setText("Discount");

        jLabel10.setText("Total Harga Tiket");

        jLabel11.setText("Pembayaran");

        buttonGroup2.add(Cash);
        Cash.setText("Cash");

        buttonGroup2.add(Kredit);
        Kredit.setText("KartuKredit");

        jLabel12.setText("Potongan Pembayaran");

        txtfield7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield7ActionPerformed(evt);
            }
        });

        jLabel13.setText("Harga Yang Harus Dibayar");

        btnjumlahharga.setText("JumlahHarga");
        btnjumlahharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjumlahhargaActionPerformed(evt);
            }
        });

        btnHargaBayar.setText("Harga Bayar");
        btnHargaBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaBayarActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        Kembalibtn.setText("Kembali");
        Kembalibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalibtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnjumlahharga)
                        .addGap(18, 18, 18)
                        .addComponent(btnHargaBayar)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(txtfield7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(txtfield8)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 123, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PulangPergi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Sejalan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtfield1)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtfield3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtfield4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Kredit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtfield5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtfield6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kembalibtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addComponent(Sejalan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PulangPergi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfield5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtfield6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Cash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Kredit)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtfield7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtfield8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnjumlahharga)
                    .addComponent(btnHargaBayar)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar)
                    .addComponent(Kembalibtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboActionPerformed
        // TODO add your handling code here:
        
         if (Combo.getSelectedItem()=="Silahkan DIpilih") {
            txtfield1.setText("");
            txtfield2.setText("");
        } else if (Combo.getSelectedItem()=="GARUDA") {
            txtfield1.setText("JKT-BALI");
            txtfield2.setText("1000000");
        } else if (Combo.getSelectedItem()=="MERPATI") {
            txtfield1.setText("JKT-LOMBOK");
            txtfield2.setText("800000");
        } else if (Combo.getSelectedItem()=="MANDALA") {
            txtfield1.setText("JKT-JATIM");
            txtfield2.setText("700000");
        } else if (Combo.getSelectedItem()=="LION AIR") {
            txtfield1.setText("JKT-MEDAN");
            txtfield2.setText("500000");
        } else if (Combo.getSelectedItem()=="SEMPATI") {
            txtfield1.setText("JKT-RIAU");
            txtfield2.setText("850000");
        }
    }//GEN-LAST:event_ComboActionPerformed

    private void txtfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield2ActionPerformed

    private void txtfield3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield3ActionPerformed

    private void txtfield4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield4ActionPerformed

    private void PulangPergiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulangPergiActionPerformed
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_PulangPergiActionPerformed
    
    private void btnjumlahhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjumlahhargaActionPerformed
        // TODO add your handling code here:
        

      
Integer HargaTiket = Integer.parseInt(txtfield2.getText());
Integer JumlahDibeli = Integer.parseInt(txtfield3.getText());

double HasilHarga = HargaTiket * JumlahDibeli;
txtfield4.setText(String.valueOf(HasilHarga));

double discount = 0;
if (PulangPergi.isSelected()) {
    discount = HasilHarga * 0.10;
} else if (Sejalan.isSelected()) {
    discount = 0;
}
txtfield5.setText(String.valueOf(discount));

double RealHargaaa = 0;
if (PulangPergi.isSelected()) {
    RealHargaaa = HasilHarga - discount;
} else if (Sejalan.isSelected()) {
    RealHargaaa = HasilHarga;
}
txtfield6.setText(String.valueOf(RealHargaaa));

       
       
    
       
       
        
        
        
    }//GEN-LAST:event_btnjumlahhargaActionPerformed

    private void btnHargaBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaBayarActionPerformed
        // TODO add your handling code here:
     
double NewDisc = 0;
double HargaPembayaran = 0;






double RealHargaaa = Double.parseDouble(txtfield6.getText());

if(Cash.isSelected()) {
    NewDisc = RealHargaaa * 0.05; 
    HargaPembayaran = RealHargaaa - NewDisc; 
} else if (Kredit.isSelected()) {
    NewDisc = 0; 
    HargaPembayaran = RealHargaaa;
}


txtfield7.setText(String.valueOf(NewDisc));
txtfield8.setText(String.valueOf(HargaPembayaran));

        
        
    }//GEN-LAST:event_btnHargaBayarActionPerformed

    
    
    private void SejalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SejalanActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_SejalanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        txtfield1.setText("");
        txtfield2.setText("");
        txtfield3.setText("");
        txtfield4.setText("");
        txtfield5.setText("");
        txtfield6.setText("");
        txtfield7.setText("");
        txtfield8.setText("");
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void txtfield7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield7ActionPerformed

    private void KembalibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalibtnActionPerformed
        // TODO add your handling code here:
        
         menuperjalanan A = new menuperjalanan();
        A.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KembalibtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perjalanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cash;
    private javax.swing.JComboBox<String> Combo;
    private javax.swing.JToggleButton Kembalibtn;
    private javax.swing.JRadioButton Kredit;
    private javax.swing.JRadioButton PulangPergi;
    private javax.swing.JRadioButton Sejalan;
    private javax.swing.JToggleButton btnHargaBayar;
    private javax.swing.JToggleButton btnhapus;
    private javax.swing.JToggleButton btnjumlahharga;
    private javax.swing.JToggleButton btnkeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtfield1;
    private javax.swing.JTextField txtfield2;
    private javax.swing.JTextField txtfield3;
    private javax.swing.JTextField txtfield4;
    private javax.swing.JTextField txtfield5;
    private javax.swing.JTextField txtfield6;
    private javax.swing.JTextField txtfield7;
    private javax.swing.JTextField txtfield8;
    // End of variables declaration//GEN-END:variables
}
